In [7]:
import numpy as np

In [21]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
np.array([[2,2,2,2],[1,1,1,1]])

array([[2, 2, 2, 2],
       [1, 1, 1, 1]])

In [23]:
np.array([1,1,1,1])

array([1, 1, 1, 1])

In [24]:
mi_lista = [0, 2, 5.5, 4, 6, 9]

In [25]:
np.array(mi_lista)

array([0. , 2. , 5.5, 4. , 6. , 9. ])

In [28]:
np.zeros(10).reshape(5,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
np.ones(12).reshape(3,2,2)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [40]:
array_pablo = np.full(shape = (5,5), fill_value = 1)

In [43]:
base = np.linspace(2, 6, 5)
base 

array([2., 3., 4., 5., 6.])

In [46]:
np.full_like(base, np.pi)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265])

In [50]:
np.random.rand(1)

array([0.02283147])

In [51]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [53]:
np.random.uniform(low = 1, high= 2, size = 5)

array([1.50010129, 1.72954401, 1.92407241, 1.99970803, 1.57703034])

In [54]:
np.random.randn(2,2)

array([[ 6.18432218e-01, -1.86831927e+00],
       [-2.11282850e-01,  1.58436722e-03]])

In [55]:
np.random.normal(loc = 0, scale = 2, size = 10)

array([ 1.92720994,  2.43769051, -0.48061204, -1.05666935, -0.70231096,
        0.02538132,  2.18877779, -1.36626203, -1.9226311 , -1.40602299])

In [59]:
mi_lista_2 = [[2,2],[3,3],[4,4]]
mi_array_2 = np.array(mi_lista_2)

In [57]:
np.random.randint(low = 1, high = 10, size = 10)

array([9, 5, 9, 5, 2, 8, 6, 6, 3, 1])

In [60]:
mi_array_2.shape

(3, 2)

In [66]:
mi_array_2.reshape(2,3)

array([[2, 2, 3],
       [3, 4, 4]])

In [63]:
mi_array_2

array([[2, 2],
       [3, 3],
       [4, 4]])

In [74]:
a = [2,2,2]
b = a.copy()
b[0] = 10
# para que no nos pase
mi_array_2_copia = mi_array_2.copy()

In [76]:
for i in mi_array_2:
    print(i)

[2 2]
[3 3]
[4 4]


In [77]:
A = np.arange(8).reshape(2,2,2)
B = np.ones(8).reshape(2,2,2)

In [78]:
A,B

(array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]),
 array([[[1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.]]]))

In [80]:
A - B

array([[[-1.,  0.],
        [ 1.,  2.]],

       [[ 3.,  4.],
        [ 5.,  6.]]])

In [84]:
matriz_a = np.mat(([2,2],[2,3]))

In [87]:
matriz_a.I #matriz inversa

matrix([[ 1.5, -1. ],
        [-1. ,  1. ]])

In [88]:
np.mean([2,3,2,2,2])

2.2

In [89]:
np.median([1,2,4,5,67,3,22,3])

3.5

In [90]:
np.std([1,2,3,4,5,64,32,245,10000])

3129.5881163146337

In [96]:
np.exp(np.e), np.log(10), np.sqrt(10)

(15.154262241479262, 2.302585092994046, 3.1622776601683795)

In [95]:
np.sqrt(mi_array_2)

array([[1.41421356, 1.41421356],
       [1.73205081, 1.73205081],
       [2.        , 2.        ]])

In [ ]:
# np.asmatrix(), np.asarray()

In [101]:
%%timeit
a = np.arange(1000)
b = np.zeros(1000)
a + a

4.85 µs ± 407 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [100]:
%%timeit
a = np.arange(1000)
b = np.zeros(1000)
i = 0
for j in a:
    b[i] = j + j
    i += 1 

284 µs ± 21.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [103]:
np.array([[None,1],[1,2]])

array([[None, 1],
       [1, 2]], dtype=object)

In [104]:
np.array([[np.nan,1],[1,2]])

array([[nan,  1.],
       [ 1.,  2.]])

In [106]:
mi_array_3 = np.arange(0,10).reshape(2,5)
print(mi_array_3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [108]:
4 % 2

0

In [1]:
filtro = ((mi_array_3 % 2) == 0) & mi_array_3 > 0

NameError: name 'mi_array_3' is not defined

In [110]:
filtro

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [111]:
mi_array_3[filtro]

array([0, 2, 4, 6, 8])

In [112]:
0 % 2 

0